// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuanLyDKHP.Infrastructure.Data;

#nullable disable

namespace QuanLyDKHP.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918065055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.CauHinhHeThong", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Key");

                    b.ToTable("CauHinhHeThong", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "SoTinChiToiThieu",
                            MoTa = "Số TC tối thiểu/học kỳ",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "10"
                        },
                        new
                        {
                            Key = "SoTinChiToiDa",
                            MoTa = "Số TC tối đa/học kỳ",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "25"
                        },
                        new
                        {
                            Key = "DonGiaTinChiLT",
                            MoTa = "Đơn giá 1 TC lý thuyết (VNĐ)",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "500000"
                        },
                        new
                        {
                            Key = "DonGiaTinChiTH",
                            MoTa = "Đơn giá 1 TC thực hành (VNĐ)",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "700000"
                        });
                });

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.DangKyHocPhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DiemChu")
                        .HasColumnType("varchar(5)");

                    b.Property<decimal?>("DiemSo")
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("HinhThucDK")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaLHP")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("NgayDK")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NguoiDK")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SoTienDaDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("SoTienPhaiDong")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("DangHoc");

                    b.HasKey("Id");

                    b.HasIndex("MaLHP");

                    b.HasIndex("MaSV", "MaLHP")
                        .IsUnique();

                    b.ToTable("DangKyHocPhan", (string)null);
                });

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.HocKy", b =>
                {
                    b.Property<string>("MaHocKy")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("DangMo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaHocKy");

                    b.ToTable("HocKy", (string)null);
                });

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.LopHocPhan", b =>
                {
                    b.Property<string>("MaLHP")
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("GiangDayOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LoaiHinhDT")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaGV")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaHocKy")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("SiSoToiDa")
                        .HasColumnType("integer");

                    b.HasKey("MaLHP");

                    b.HasIndex("MaHocKy");

                    b.HasIndex("MaMon", "MaHocKy");

                    b.ToTable("LopHocPhan", (string)null);
                });

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.MonHoc", b =>
                {
                    b.Property<string>("MaMon")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BacDaoTao")
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("SoTinChiLT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SoTinChiTH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("MaMon");

                    b.ToTable("MonHoc", null, t =>
                        {
                            t.HasCheckConstraint("CK_MonHoc_SoTinChi", "\\\"SoTinChiLT\\\" + \\\"SoTinChiTH\\\" > 0");
                        });
                });

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MaGV")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("HoatDong");

                    b.HasKey("Id");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoTen = "Quản trị viên",
                            IsDeleted = false,
                            MatKhauHash = "$2a$11$0W50cW0wYl.VzIeQ5p3oVuZg1hK.z11U9mS./2T/Gg2RjQYx2eO7O",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Admin",
                            TenDangNhap = "admin",
                            TrangThai = "HoatDong"
                        });
                });

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("KhoaHoc")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LopSinhHoat")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MaSV");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.DangKyHocPhan", b =>
                {
                    b.HasOne("QuanLyDKHP.Core.Entities.LopHocPhan", "LopHocPhan")
                        .WithMany("DangKyHocPhans")
                        .HasForeignKey("MaLHP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDKHP.Core.Entities.SinhVien", "SinhVien")
                        .WithMany("DangKyHocPhans")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.LopHocPhan", b =>
                {
                    b.HasOne("QuanLyDKHP.Core.Entities.HocKy", "HocKy")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyDKHP.Core.Entities.MonHoc", "MonHoc")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.HocKy", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.LopHocPhan", b =>
                {
                    b.Navigation("DangKyHocPhans");
                });

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.MonHoc", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("QuanLyDKHP.Core.Entities.SinhVien", b =>
                {
                    b.Navigation("DangKyHocPhans");
                });
#pragma warning restore 612, 618
        }
    }
}
